Ubuntu 23.10 GCC 13.2 fixups
skaarj1989/SupernovaEngine pull request #5
Opened 2024-03-23 10:41 UTC by boberfly

Hi @skaarj1989 

Your engine looked really cool so I thought I'd give it a spin. Here's some of the changes I needed to do to get it to compile for me. Some are probably not ideal like needing to comment out the `#pragma region/endregion` but I thought I'd share anyways.
 
`MaterialConverter.cpp` I needed to move `has_flags`, GCC wasn't allowing template specialization in an anonymous namespace, I couldn't find a better solution here.

Editor launches and I'm able to load the samples correctly on an AMD Radeon 6900XT RADV driver, 120fps. Material editor is a segfault for me though and I've not run it through a debugger yet.

Kind regards

2024-03-23 12:52 UTC, skaarj1989 commented on modules/RHI/Vulkan/src/RenderDevice.cpp
I'd just add `static`, right before `constexpr`.

2024-03-23 12:53 UTC, skaarj1989 commented on modules/Scripting/modules/Emitter/include/LuaEmitter.hpp
I keep forgetting about these when working on **msvc**.

2024-03-23 12:58 UTC, skaarj1989 commented on tools/Editor/include/MaterialEditor/NodeFactoryRegistry.hpp
GCC complains about `Storage` being `private`. Right here:
https://github.com/skaarj1989/SupernovaEngine/blob/55adc6d9394e031053dd80a76705202ae3fa3834/tools/Editor/src/MaterialEditor/NodeFactoryRegistry.cpp#L65

I see two ways to solve this:
Move `Storage` alias to `public` section or use `auto &` instead of `NodeFactoryRegistry::Storage &`.

2024-03-23 13:00 UTC, skaarj1989 commented on tools/Editor/src/MaterialEditor/GraphCommands.cpp
These fixes only the compiler error. Once you run the Material Editor you'll get messages like this one:
`[" __FUNCTION__ "][node_id=14] Created (factory_id=17856740819158826021)`

2024-03-23 13:02 UTC, skaarj1989 commented on tools/Editor/src/MaterialEditor/NodeFactoryRegistry.cpp
Looks like GCC doesn't like pragmas inside initializer lists (`#pragma is not allowed here`).
I'd just remove them.

2024-03-23 13:11 UTC, skaarj1989 commented on tools/MeshConverter/src/MaterialConverter.cpp
What do you think about moving `TextureFlags` outside anonymous namespace?

2024-03-23 13:13 UTC, skaarj1989 commented on tools/MeshConverter/src/glm2ai.cpp
Do you have a compiler error without `matrix4x4.inl`?
I don't get any in **GCC 13.1**

2024-03-23 13:29 UTC, skaarj1989 commented
Hi @boberfly

I've ignored the Linux build for too long ...

Thanks for the PR and reporting the issue with **Material Editor**, I've already investigated the problem. It's right here:
https://github.com/skaarj1989/SupernovaEngine/blob/55adc6d9394e031053dd80a76705202ae3fa3834/tools/Editor/src/MaterialEditor/MaterialEditor.cpp#L380

`nullptr` when the project is not initialized, and this happens when the **Editor** is run without a project path as a command line argument (which I always use for convenience).

2024-03-23 15:40 UTC, skaarj1989 requested changes
You are almost there, I'll merge this PR once you fix the mentioned issues.
(Ignore the segfault, I'll take care of this one).

2024-03-23 15:40 UTC, skaarj1989 commented on tools/MeshConverter/CMakeLists.txt
What does this solve?

2024-03-24 03:03 UTC, boberfly commented on tools/Editor/src/MaterialEditor/NodeFactoryRegistry.cpp
I did read that commenting them out, the pragmas still work under visual studio to categorise the UI - are you able to confirm that before I clear them out?

2024-03-24 03:07 UTC, boberfly commented on tools/MeshConverter/src/glm2ai.cpp
It was the linker having troubles with finding `aiMatrix4x4t<TReal>::aiMatrix4x4t()` but it makes sense as it's inline and would need to be included like I've got here. Did Assimp sourcecode remove `#include "matrix4x4.int"` from the end of `matrix4x4.h` by chance? Odd that the older compiler was fine with this...

2024-03-24 03:10 UTC, boberfly commented on tools/MeshConverter/CMakeLists.txt
https://github.com/assimp/assimp/issues/5315 this one here, maybe I can just conditional it for only GCC compilers?

2024-03-24 03:13 UTC, boberfly commented on modules/RHI/Vulkan/src/RenderDevice.cpp
Done

2024-03-24 03:13 UTC, boberfly commented on tools/Editor/include/MaterialEditor/NodeFactoryRegistry.hpp
I kept it private and went with the `auto &` which seemed to work here, cheers.

2024-03-24 03:13 UTC, boberfly commented on tools/MeshConverter/src/MaterialConverter.cpp
Sounds good, that was my alternate approach which did work before and looks cleaner.

2024-03-24 03:15 UTC, boberfly commented on tools/Editor/src/MaterialEditor/GraphCommands.cpp
Yep all good, just GCC being pedantic with strings.

2024-03-24 08:10 UTC, boberfly commented on tools/Editor/src/MaterialEditor/GraphCommands.cpp
And @skaarj1989 gave me more clarity on this one, should be ok now.

2024-03-24 08:52 UTC, skaarj1989 reviewed
LGTM

2024-03-24 08:52 UTC, skaarj1989 commented on tools/Editor/src/MaterialEditor/NodeFactoryRegistry.cpp
It does not work for me; even if it did, it looks ugly. I'd remove these.

2024-03-24 08:53 UTC, skaarj1989 commented
Thank you for your work!

2024-03-24 08:53 UTC, merged